name: itsale
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  get_storage:
  cupertino_icons: ^1.0.6
#  gallery_saver: ^2.3.2
  media_store_plus: ^0.1.3

  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
dependency_overrides:
  http: ^0.13.6
  flutter_screenutil: ^5.9.3
#  gallery_saver: ^2.3.2
  flutter_localizations:
    sdk: flutter
  svg_flutter: ^0.0.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  flutter_credit_card: ^4.0.1
  lottie: ^3.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^8.2.1
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  motion_toast: ^2.11.0
  shared_preferences:
  url_launcher:
  image_picker:
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.9
  flutter_echarts: ^2.5.0
  drop_down_search_field: ^1.0.6
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  webview_flutter:
  flutter_map: ^7.0.2
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^29.1.41
  badges: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  material_design_icons_flutter: 7.0.7296
  flutter_svg: ^2.1.0
  pin_code_fields: ^8.0.1
  animated_snack_bar: ^0.4.0
  restart_app: ^1.3.2
  app_links: ^3.4.1
  audioplayers: ^6.4.0

  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  

  typed_data: ^1.4.0















flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/playstore.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/fonts/
    - assets/svgs/
    - assets/lang/
    - assets/sounds/bell-notification-337658.mp3

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets\fonts\Tajawal-Regular.ttf
          weight: 700

flutter_intl:
  enabled: true
